# Generated by Django 4.2.13 on 2024-10-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='N/A', max_length=10, null=True),
        ),
    ]
