# Generated by Django 4.2.13 on 2024-06-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(fields=('manager_id', 'league_id'), name='unique_manager_in_league'),
        ),
    ]
