# Generated by Django 4.2.13 on 2024-10-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0002_remove_player_name_player_age_player_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
