# Generated by Django 4.2.13 on 2024-06-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0003_leaguemembership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='league_id',
        ),
    ]
