# Generated by Django 4.2.13 on 2024-10-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0003_alter_player_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
