# Generated by Django 4.2.13 on 2024-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('num_of_teams', models.IntegerField()),
                ('sport', models.CharField(max_length=25)),
                ('league_name', models.CharField(max_length=255)),
                ('previous_league_id', models.BigIntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
