# Generated by Django 4.2.13 on 2024-10-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0006_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery_sim.league')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery_sim.manager')),
            ],
            options={
                'unique_together': {('manager', 'league')},
            },
        ),
    ]
