# Generated by Django 4.2.13 on 2024-11-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0010_remove_manager_losses_remove_manager_points_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='points_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='points_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='record',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
