# Generated by Django 4.2.13 on 2024-11-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_sim', '0011_manager_losses_manager_points_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='roster',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
    ]
